version: "3.7"
services:
  eve-postgres:
    image: fallenreaper/eve-postgres:latest
    hostname: eve-postgres
    ports:
      - 8888:5432
    networks:
      - aboranet
  client:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      - POSTGRES_HOST=eve-postgres
      - POSTGRES_PORT=5432
    depends_on:
      - eve-postgres
    command: ['./waitforcontainer.sh', 'eve-postgres', 'npm', 'start']
    networks:
      - aboranet
networks:
  aboranet:
    external:
      name: aboranet
